### ISSUE TITLE
Rename to either `dart_rviz` or `dart_interactivemarker`

### ISSUE THREAD

**Issue by psigen** [personalrobotics/dart_rviz#2]
Currently, the source code is divided between calling the package `dart_interactivemarker` (github repo, python module name) and calling it `dart_rviz` (c++ namespace, CMakeLists.txt).

For the sake of all that is good in the world, we should pick a particular name and stick with it.

**Comment by mkoval** [comment]
Lets go with `dart_rviz`. It's (much) shorter than `dart_interactivemarker` and consistent with the naming of `or_rviz`.

**Comment by psigen** [comment]
Addressed in #3.
